### ISSUE TITLE
can not get object detection to work. errors when i run zm_detect.py

### ISSUE THREAD

**Issue by dfgas** [dlandon/zoneminder#126]
I am sure I am missing something somewhere but after 5 or 6 tries, it is time to ask for help. anyone have an idea?

2020-10-20 10:04:36.720495 zmc_m3[14587].INF-zm_monitor.cpp/2550 [Monitor-3: images:17400 - Capturing at 16.67 fps, capturing bandwidth 112328bytes/sec]
2020-10-20 10:04:36.012975 zma_m1[14554].INF-zm_monitor.cpp/1305 [Monitor-1: 18800 - Analysing at 14.29 fps]
2020-10-20 10:04:35.147348 zmc_m1[14539].INF-zm_monitor.cpp/2550 [Monitor-1: images:18800 - Capturing at 14.29 fps, capturing bandwidth 106500bytes/sec]
2020-10-20 10:04:33.829523 zmc_m2[15273].INF-zm_monitor.cpp/2550 [Monitor-2: images:3400 - Capturing at 16.67 fps, capturing bandwidth 242283bytes/sec]
2020-10-20 10:04:31.648792 zmesdetect[15367].FAT-zm_detect.py/240 [error: Traceback:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/zmes_hook_helpers/utils.py", line 175, in download_files
    input_file = opener.open(url)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zm_detect.py", line 237, in main_handler
    args)
  File "/usr/local/lib/python3.6/dist-packages/zmes_hook_helpers/utils.py", line 177, in download_files
    g.logger.Error(e)
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ZMLog.py", line 373, in Error
    _log('ERR',message,caller)
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ZMLog.py", line 306, in _log
    conn.execute(cmd)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/dist-packages/mysql/connector/cursor_cext.py", line 248, in execute
    prepared = self._cnx.prepare_for_mysql(params)
  File "/usr/local/lib/python3.6/dist-packages/mysql/connector/connection_cext.py", line 647, in prepare_for_mysql
    result[key] = self._cmysql.convert_to_mysql(value)[0]
_mysql_connector.MySQLInterfaceError: Python type HTTPError cannot be converted
]
2020-10-20 10:04:31.615802 zmesdetect[15367].ERR-zm_detect.py/239 [Error downloading files: Python type HTTPError cannot be converted]
2020-10-20 10:04:31.469610 zmesdetect[15367].INF-zm_detect.py/225 [Importing local classes for Object/Face]
2020-10-20 10:04:31.438737 zmesdetect[15367].INF-utils.py/360 [Ignoring monitor specific settings, as you did not provide a monitor id]
2020-10-20 10:04:31.356391 zmesdetect[15367].INF-zm_detect.py/196 [---------| hook version: 0.1.30, ES version: 6.0.4 , OpenCV version: 4.2.0|------------]
2020-10-20 10:04:30.998122 zma_m3[14598].INF-zm_monitor.cpp/1305 [Monitor-3: 17300 - Analysing at 16.67 fps]

**Comment by dfgas** [comment]
well i got a little farther but I am not sure on the issue here


Date/Time | Component | Server | PID | Level | Message | File | Line
-- | -- | -- | -- | -- | -- | -- | --
2020-10-20 10:37:17 | zmc_m2 |   | 969 | INF | Monitor-2: images:2000 - Capturing at 14.29 fps, capturing bandwidth 210067bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:15 | zma_m3 |   | 1013 | INF | Monitor-3: 2000 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:37:14 | zmc_m3 |   | 973 | INF | Monitor-3: images:2000 - Capturing at 14.29 fps, capturing bandwidth 103557bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:14 | zma_m1 |   | 997 | INF | Monitor-1: 2000 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:37:13 | zmc_m1 |   | 961 | INF | Monitor-1: images:2000 - Capturing at 14.29 fps, capturing bandwidth 103423bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:10 | zmc_m2 |   | 969 | INF | Monitor-2: images:1900 - Capturing at 14.29 fps, capturing bandwidth 208612bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:08 | zma_m3 |   | 1013 | INF | Monitor-3: 1900 - Analysing at 16.67 fps | zm_monitor.cpp | 1305
2020-10-20 10:37:07 | zmc_m3 |   | 973 | INF | Monitor-3: images:1900 - Capturing at 16.67 fps, capturing bandwidth 122699bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:07 | zma_m1 |   | 997 | INF | Monitor-1: 1900 - Analysing at 16.67 fps | zm_monitor.cpp | 1305
2020-10-20 10:37:06 | zmc_m1 |   | 961 | INF | Monitor-1: images:1900 - Capturing at 16.67 fps, capturing bandwidth 123496bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:03 | zmc_m2 |   | 969 | INF | Monitor-2: images:1800 - Capturing at 14.29 fps, capturing bandwidth 194948bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:02 | zma_m3 |   | 1013 | INF | Monitor-3: 1800 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:37:01 | zmc_m3 |   | 973 | INF | Monitor-3: images:1800 - Capturing at 14.29 fps, capturing bandwidth 94872bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:37:01 | zma_m1 |   | 997 | INF | Monitor-1: 1800 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:37:00 | zmc_m1 |   | 961 | INF | Monitor-1: images:1800 - Capturing at 14.29 fps, capturing bandwidth 92624bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:56 | zmc_m2 |   | 969 | INF | Monitor-2: images:1700 - Capturing at 14.29 fps, capturing bandwidth 209141bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:55 | zma_m3 |   | 1013 | INF | Monitor-3: 1700 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:54 | zma_m1 |   | 997 | INF | Monitor-1: 1700 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:54 | zmc_m3 |   | 973 | INF | Monitor-3: images:1700 - Capturing at 14.29 fps, capturing bandwidth 106515bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:53 | zmc_m1 |   | 961 | INF | Monitor-1: images:1700 - Capturing at 14.29 fps, capturing bandwidth 107024bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:49 | zmc_m2 |   | 969 | INF | Monitor-2: images:1600 - Capturing at 16.67 fps, capturing bandwidth 243066bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:48 | zma_m3 |   | 1013 | INF | Monitor-3: 1600 - Analysing at 16.67 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:47 | zma_m1 |   | 997 | INF | Monitor-1: 1600 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:47 | zmc_m3 |   | 973 | INF | Monitor-3: images:1600 - Capturing at 16.67 fps, capturing bandwidth 122865bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:46 | zmc_m1 |   | 961 | INF | Monitor-1: images:1600 - Capturing at 16.67 fps, capturing bandwidth 124503bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:43 | zmc_m2 |   | 969 | INF | Monitor-2: images:1500 - Capturing at 14.29 fps, capturing bandwidth 196889bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:42 | zma_m3 |   | 1013 | INF | Monitor-3: 1500 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:41 | zmc_m3 |   | 973 | INF | Monitor-3: images:1500 - Capturing at 14.29 fps, capturing bandwidth 93978bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:40 | zmc_m1 |   | 961 | INF | Monitor-1: images:1500 - Capturing at 14.29 fps, capturing bandwidth 93903bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:40 | zma_m1 |   | 997 | INF | Monitor-1: 1500 - Analysing at 16.67 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:36 | zmc_m2 |   | 969 | INF | Monitor-2: images:1400 - Capturing at 14.29 fps, capturing bandwidth 209412bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:35 | zma_m3 |   | 1013 | INF | Monitor-3: 1400 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:34 | zmc_m3 |   | 973 | INF | Monitor-3: images:1400 - Capturing at 14.29 fps, capturing bandwidth 106701bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:34 | zma_m1 |   | 997 | INF | Monitor-1: 1400 - Analysing at 14.29 fps | zm_monitor.cpp | 1305
2020-10-20 10:36:33 | zmc_m1 |   | 961 | INF | Monitor-1: images:1400 - Capturing at 14.29 fps, capturing bandwidth 104994bytes/sec | zm_monitor.cpp | 2550
2020-10-20 10:36:30 | zmesdetect |   | 1070 | FAT | Unrecoverable error:OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream' Traceback:Traceback (most recent call last): File "./zm_detect.py", line 850, in <module> main_handler() File "./zm_detect.py", line 321, in main_handler m = object_detection.Object(logger=g.logger, options=g.config) File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/object.py", line 26, in __init__ self.model = yolo.Yolo(options=options, logger=logger) File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/yolo.py", line 59, in __init__ config_file_abs_path)cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream' | zm_detect.py | 853
2020-10-20 10:36:29 | zmesdetect |   | 1070 | INF | Importing local classes for Object/Face | zm_detect.py | 225
2020-10-20 10:36:29 | zmesdetect |   | 1070 | INF | Ignoring monitor specific settings, as you did not provide a monitor id | utils.py | 360
2020-10-20 10:36:29 | zmesdetect |   | 1070 | INF | ---------\| hook version: 0.1.30, ES version: 6.0.4 , OpenCV version: 4.2.0\|------------ | zm_detect.py

**Comment by dfgas** [comment]
hmmm, this might be a conflict with opencv 4.2.0 and yolov4. redoing it again with yolov3

**Comment by dfgas** [comment]
that was the fix for that
