### ISSUE TITLE
Problem with zm_detect.py

### ISSUE THREAD

**Issue by joselito11** [dlandon/zoneminder#67]
I can not start zm_detect.py:
```
sudo -u www-data /mnt/Zoneminder/hook/zm_event_start.sh 1 1
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 134, in <module>
    log.init(process_name='zmesdetect_'+'m'+args['monitorid'])
  File "/usr/local/lib/python3.7/dist-packages/zmes_hook_helpers/log.py", line 35, in init
    g.logger = wrapperLogger(name=process_name, dump_console=dump_console)
  File "/usr/local/lib/python3.7/dist-packages/zmes_hook_helpers/log.py", line 10, in __init__
    zmlog.init(name=name)
  File "/usr/local/lib/python3.7/dist-packages/pyzm/ZMLog.py", line 131, in init
    with open(f) as s:
NotADirectoryError: [Errno 20] Not a directory: '/etc/zm/zm.conf'
```
or this:
```
sudo -u www-data /mnt/Zoneminder/hook/zm_event_start.sh 500 2
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 134, in <module>
    log.init(process_name='zmesdetect_'+'m'+args['monitorid'])
  File "/usr/local/lib/python3.7/dist-packages/zmes_hook_helpers/log.py", line 35, in init
    g.logger = wrapperLogger(name=process_name, dump_console=dump_console)
  File "/usr/local/lib/python3.7/dist-packages/zmes_hook_helpers/log.py", line 10, in __init__
    zmlog.init(name=name)
  File "/usr/local/lib/python3.7/dist-packages/pyzm/ZMLog.py", line 144, in init
    config['logpath'] =  config_file['zm_root']['ZM_PATH_LOGS']
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'ZM_PATH_LOGS'
```
I reinstalled with:
```
sudo docker run -d --name="Zoneminder" --net="bridge" --privileged="true" -p 888:80/tcp -p 9001:9001/tcp -e TZ="Europe/Berlin" -e SHMEM="50%" -e PUID="1000" -e PGID="1000" -e INSTALL_HOOK="1" -e INSTALL_FACE="1" -e INSTALL_TINY_YOLO="1" -e INSTALL_YOLO="0" -v "/mnt/Zoneminder":"/config":rw -v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw dlandon/zoneminder
```
but wont get folder /etc/zm/

**Comment by dlandon** [comment]
You'll need to try Zoneminder forums for help.  I can't help with the particulars of ES.

**Comment by joselito11** [comment]
Installed without volume option, and it is working now:
```
-v "/mnt/Zoneminder":"/config":rw \
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw \
```
